import React from "react";
import { getAudit } from "../api";

export default function InsightsPanel({
  summary,
  events,
  onSeek,
  activeVersion,
  jobId,
  fileHash,
  filename,
  analyzedAt,
}) {
  const isV2 = activeVersion === "v2";

  async function handleDownloadReport() {
    console.log("[EvidenceReport] button clicked, jobId:", jobId);
    try {
      console.log("[EvidenceReport] fetching audit for job:", jobId);
      const audit = await getAudit(jobId);
      console.log("[EvidenceReport] audit data received:", audit);

      const eventsText = events
        .map((e) => `${e.timestamp} — ${e.label}\n${e.description}`)
        .join("\n\n");

      const report = [
        "================================",
        "HALOS VIDEO INSIGHT ASSISTANT",
        "Evidence Analysis Report v2.0",
        "================================",
        `File: ${audit.filename}`,
        `SHA-256: ${audit.file_hash}`,
        `Analyzed: ${audit.analyzed_at}`,
        `Model: ${audit.model_used}`,
        "================================",
        "SUMMARY",
        summary,
        "================================",
        "KEY EVENTS",
        eventsText,
        "================================",
        "This report was generated by HALOS Video Insight Assistant.",
        "Original file integrity has been verified via SHA-256 hash.",
      ].join("\n");

      console.log("[EvidenceReport] report built, triggering download");
      const blob = new Blob([report], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${(audit.filename || "video").replace(/\.[^.]+$/, "")}_evidence_report.txt`;
      // Must be in the DOM for Firefox/Safari to fire the download
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      // Revoke after a tick so the browser has time to start the download
      setTimeout(() => URL.revokeObjectURL(url), 100);
      console.log("[EvidenceReport] download triggered");
    } catch (err) {
      console.error("[EvidenceReport] failed:", err);
    }
  }

  return (
    <div className="flex flex-col bg-brand-surface rounded-lg border border-brand-border overflow-hidden flex-1 min-h-0">
      {/* Header */}
      <div className="px-4 py-3 border-b border-brand-border flex items-center justify-between">
        <div>
          <h2 className="text-sm font-semibold text-slate-200 uppercase tracking-wider">
            AI Summary
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            {isV2 ? "v2.0 — Vision + Integrity" : "v1.0 — Text Analysis Only"}
          </p>
        </div>
        {isV2 && (
          <button
            onClick={handleDownloadReport}
            className="text-xs text-brand-orange border border-brand-orange px-2.5 py-1 rounded-lg hover:bg-brand-orange hover:text-white transition-colors font-semibold shrink-0"
          >
            Download Evidence Report
          </button>
        )}
      </div>

      {/* Summary */}
      <div className="px-4 py-3 border-b border-brand-border">
        <p className="text-sm text-slate-300 leading-relaxed">{summary}</p>
      </div>

      {/* Evidence Integrity (v2 only) */}
      {isV2 && fileHash && (
        <div className="px-4 py-3 border-b border-brand-border bg-green-950/30">
          <div className="flex items-center gap-2 mb-1.5">
            <span className="text-green-400 text-sm">✓</span>
            <span className="text-xs font-semibold text-green-400 uppercase tracking-wider">
              Evidence Integrity
            </span>
          </div>
          <p className="text-xs text-slate-400 mb-1">Original file hash verified</p>
          <p className="text-xs font-mono text-slate-300 bg-brand-bg rounded px-2 py-1 mb-1.5">
            {fileHash.slice(0, 16)}…
          </p>
          {analyzedAt && (
            <p className="text-xs text-slate-500">
              Analyzed: {new Date(analyzedAt).toLocaleString()}
            </p>
          )}
          <p className="text-xs text-slate-500">Model: GPT-4o Vision</p>
        </div>
      )}

      {/* Key Events header */}
      <div className="px-4 py-2 border-b border-brand-border">
        <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
          Key Events
        </h3>
      </div>

      <div className="overflow-y-auto flex-1">
        {events.map((event, i) => (
          <EventRow key={i} event={event} onSeek={onSeek} />
        ))}
      </div>
    </div>
  );
}

export function EventRow({ event, onSeek }) {
  return (
    <button
      onClick={() => onSeek(event.seconds)}
      className="w-full text-left px-4 py-3 border-b border-brand-border hover:bg-white/5 transition-colors flex gap-3 items-start group"
    >
      <span className="shrink-0 mt-0.5 px-2 py-0.5 bg-brand-orange text-white text-xs font-mono rounded font-semibold">
        {event.timestamp}
      </span>
      <div className="min-w-0">
        <p className="text-sm font-semibold text-slate-200 group-hover:text-brand-orange transition-colors truncate">
          {event.label}
        </p>
        <p className="text-xs text-slate-400 mt-0.5 leading-relaxed">
          {event.description}
        </p>
      </div>
    </button>
  );
}
