import React, { useState, useRef, useEffect, useCallback } from "react";
import { uploadTactical, getTacticalStatus } from "../api";

export default function TacticalLink() {
  const [cameras, setCameras] = useState([null, null, null, null]);
  const [targetDescription, setTargetDescription] = useState("");
  const [appState, setAppState] = useState("idle"); // idle | processing | done | error
  const [processingStage, setProcessingStage] = useState(null);
  const [result, setResult] = useState(null);
  const [videoUrls, setVideoUrls] = useState([null, null, null, null]);
  
  const playerRefs = useRef([null, null, null, null]);
  const [isPlaying, setIsPlaying] = useState(false);

  const handleFileUpload = (index, file) => {
    if (!file) return;
    const newCameras = [...cameras];
    newCameras[index] = file;
    setCameras(newCameras);

    const newUrls = [...videoUrls];
    if (newUrls[index]) URL.revokeObjectURL(newUrls[index]);
    newUrls[index] = URL.createObjectURL(file);
    setVideoUrls(newUrls);
  };

  const handleAnalyze = async () => {
    const uploadedFiles = cameras.filter(c => c !== null);
    if (uploadedFiles.length < 2) return;

    setAppState("processing");
    setProcessingStage("initializing");

    try {
      const { job_id } = await uploadTactical(uploadedFiles, targetDescription);
      
      const poll = setInterval(async () => {
        try {
          const { status, stage, result } = await getTacticalStatus(job_id);
          setProcessingStage(stage);
          if (status === "done") {
            clearInterval(poll);
            setResult(result);
            setAppState("done");
          } else if (status === "error") {
            clearInterval(poll);
            setAppState("error");
          }
        } catch (err) {
          clearInterval(poll);
          setAppState("error");
        }
      }, 3000);
    } catch (err) {
      setAppState("error");
    }
  };

  const syncSeek = (seconds) => {
    playerRefs.current.forEach(ref => {
      if (ref) ref.currentTime = seconds;
    });
  };

  const togglePlay = () => {
    const nextState = !isPlaying;
    playerRefs.current.forEach(ref => {
      if (ref) {
        if (nextState) ref.play();
        else ref.pause();
      }
    });
    setIsPlaying(nextState);
  };

  const downloadReport = () => {
    if (!result) return;
    const timestamp = new Date().toLocaleString();
    const camCount = Object.keys(result.cameras).length;
    
    let report = `================================
HALOS TACTICAL-LINK
Multi-Camera Investigation Report
================================
Case Reference: ${timestamp}
Cameras Analyzed: ${camCount}
Target Description: ${targetDescription}
================================
INVESTIGATION NARRATIVE
${result.narrative}
================================
CAMERA DETECTIONS
`;

    Object.entries(result.cameras).forEach(([key, data]) => {
      report += `${key.toUpperCase()} (${data.filename}):
  SHA-256: ${data.sha256}
  Target detections: ${data.detections.length}
  First seen: ${data.detections[0]?.target_timestamp || "N/A"}
  
`;
    });

    report += `================================
CROSS-CAMERA CORRELATIONS
`;
    result.cross_camera_matches.forEach(m => {
      report += `${m.camera_a} -> ${m.camera_b}: ${m.similarity}% match at ${m.matched_at}\n`;
    });

    report += `================================
This report was generated by HALOS Tactical-Link.
All frames verified via SHA-256 hash integrity check.`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `tactical_report_${Date.now()}.txt`;
    a.click();
  };

  if (appState === "processing") {
    return (
      <div className="flex-1 flex flex-col items-center justify-center bg-[#0f1117] text-slate-200">
        <div className="text-3xl font-bold mb-8 text-brand-orange animate-pulse">TACTICAL-LINK ACTIVE</div>
        <div className="flex flex-col gap-4 w-full max-w-md">
           <div className="text-center text-sm text-slate-400 mb-2 capitalize">{processingStage?.replace(/_/g, ' ')}...</div>
           <div className="w-full bg-slate-800 h-1 rounded-full overflow-hidden">
              <div className="bg-brand-orange h-full animate-[loading_2s_infinite]" style={{width: '40%'}} />
           </div>
           <style>{`
             @keyframes loading {
               0% { transform: translateX(-100%); }
               100% { transform: translateX(300%); }
             }
           `}</style>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-1 overflow-hidden bg-[#0f1117]">
      {/* Left Panel */}
      <div className="w-[40%] border-r border-brand-border p-6 overflow-y-auto flex flex-col gap-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-100 flex items-center gap-2">
            TACTICAL-LINK <span className="text-brand-orange">★</span>
          </h1>
          <p className="text-slate-400 text-sm">Multi-Camera Evidence Reconstruction</p>
        </div>

        <div className="grid grid-cols-2 gap-4">
          {[0, 1, 2, 3].map(i => (
            <div 
              key={i}
              className={`border-2 border-dashed rounded-lg p-4 text-center cursor-pointer transition-colors ${cameras[i] ? 'border-green-500/50 bg-green-500/5' : 'border-slate-700 hover:border-brand-orange'}`}
              onClick={() => document.getElementById(`cam-upload-${i}`).click()}
            >
              <input 
                id={`cam-upload-${i}`}
                type="file"
                className="hidden"
                accept="video/mp4"
                onChange={(e) => handleFileUpload(i, e.target.files[0])}
              />
              <div className="text-xs font-bold text-slate-500 mb-2 uppercase">Camera {i+1}</div>
              {cameras[i] ? (
                <div className="flex flex-col items-center gap-1">
                  <span className="text-green-500 text-xl">✓</span>
                  <span className="text-[10px] text-slate-300 truncate w-full">{cameras[i].name}</span>
                </div>
              ) : (
                <div className="text-2xl text-slate-600">+</div>
              )}
            </div>
          ))}
        </div>

        <div className="flex flex-col gap-3">
          <label className="text-xs font-bold text-slate-500 uppercase">Camera Topology</label>
          {[0, 1, 2, 3].map(i => (
            <div key={i} className="flex items-center justify-between text-xs text-slate-300">
              <span>Camera {i+1} Adjacent to:</span>
              <select className="bg-slate-800 border border-slate-700 rounded px-2 py-1 outline-none">
                <option>None</option>
                <option selected={i === 0}>Camera 1</option>
                <option selected={i === 1}>Camera 2</option>
                <option selected={i === 2}>Camera 3</option>
                <option selected={i === 3}>Camera 4</option>
              </select>
            </div>
          ))}
        </div>

        <div className="flex flex-col gap-3">
          <label className="text-xs font-bold text-slate-500 uppercase">Target Description</label>
          <input 
            type="text"
            placeholder="e.g. silver sedan, blue jacket male"
            className="bg-slate-800 border border-slate-700 rounded-lg px-4 py-2 text-sm text-slate-200 focus:border-brand-orange outline-none"
            value={targetDescription}
            onChange={(e) => setTargetDescription(e.target.value)}
          />
        </div>

        <button 
          onClick={handleAnalyze}
          disabled={cameras.filter(c => c !== null).length < 2 || !targetDescription}
          className={`w-full py-3 rounded-lg font-bold text-sm transition-all ${cameras.filter(c => c !== null).length < 2 || !targetDescription ? 'bg-slate-800 text-slate-600 cursor-not-allowed' : 'bg-brand-orange text-white hover:bg-orange-600 shadow-lg shadow-brand-orange/20'}`}
        >
          ANALYZE ALL CAMERAS
        </button>
      </div>

      {/* Right Panel */}
      <div className="w-[60%] p-6 overflow-y-auto bg-[#0a0c10] flex flex-col gap-6">
        <section className="flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-bold text-slate-400 uppercase tracking-widest">Sync Player</h2>
            <button 
              onClick={togglePlay}
              className="px-4 py-1 bg-slate-800 hover:bg-slate-700 text-xs font-bold text-slate-200 rounded-md transition-colors"
            >
              {isPlaying ? "PAUSE ALL" : "PLAY ALL"}
            </button>
          </div>
          
          <div className="grid grid-cols-2 gap-4 aspect-video bg-black rounded-xl overflow-hidden border border-brand-border">
            {[0, 1, 2, 3].map(i => (
              <div key={i} className="relative bg-slate-900 flex items-center justify-center overflow-hidden border border-white/5">
                <div className="absolute top-2 left-2 z-10 bg-black/60 px-2 py-0.5 rounded text-[10px] font-bold text-slate-400">CAM {i+1}</div>
                {videoUrls[i] ? (
                  <video 
                    ref={el => playerRefs.current[i] = el}
                    src={videoUrls[i]}
                    className="w-full h-full object-contain"
                    onPlay={() => setIsPlaying(true)}
                    onPause={() => setIsPlaying(false)}
                  />
                ) : (
                  <div className="text-[10px] text-slate-700 font-mono">NO FEED</div>
                )}
              </div>
            ))}
          </div>
        </section>

        {result && (
          <>
            <section className="flex flex-col gap-4">
               <h2 className="text-sm font-bold text-slate-400 uppercase tracking-widest">Target Timeline</h2>
               <div className="bg-slate-900 p-4 rounded-xl border border-brand-border h-32 relative flex flex-col gap-2">
                  {Object.entries(result.cameras).map(([cam, data], idx) => (
                    <div key={cam} className="flex items-center gap-3">
                      <div className="w-12 text-[10px] font-bold text-slate-500 uppercase">{cam}</div>
                      <div className="flex-1 h-3 bg-slate-800 rounded-full relative overflow-hidden">
                        {data.detections.map((d, i) => (
                          <div 
                            key={i}
                            onClick={() => syncSeek(d.target_seconds)}
                            className="absolute h-full w-2 bg-brand-orange hover:bg-white cursor-pointer transition-colors"
                            style={{ left: `${(d.target_seconds / 120) * 100}%` }} // Simplified 120s max for scale
                            title={d.target_timestamp}
                          />
                        ))}
                      </div>
                    </div>
                  ))}
                  <div className="absolute bottom-1 right-4 text-[8px] text-slate-600 font-mono">00:00 --- SCALE: 120s --- 02:00</div>
               </div>
            </section>

            <section className="flex flex-col gap-4">
              <div className="flex items-center justify-between">
                <h2 className="text-sm font-bold text-slate-400 uppercase tracking-widest">Investigation Report</h2>
                <button 
                  onClick={downloadReport}
                  className="text-[10px] font-bold text-brand-orange hover:text-white transition-colors"
                >
                  [DOWNLOAD TACTICAL REPORT]
                </button>
              </div>
              <div className="bg-brand-surface border border-brand-border p-6 rounded-xl">
                <p className="text-slate-300 text-sm leading-relaxed mb-6 italic">
                  "{result.narrative}"
                </p>
                <div className="grid grid-cols-2 gap-4 border-t border-brand-border pt-6">
                  {Object.entries(result.cameras).map(([cam, data]) => (
                    <div key={cam} className="flex flex-col gap-1">
                      <div className="text-[10px] font-bold text-slate-500 uppercase">{cam} Hash</div>
                      <div className="text-[9px] font-mono text-slate-400 truncate">{data.sha256}</div>
                    </div>
                  ))}
                </div>
              </div>
            </section>
          </>
        )}
      </div>
    </div>
  );
}
